import type { MetadataRoute } from 'next';
import { site } from '@/lib/config';

/**
 * Dynamic sitemap.xml generated by Next.js. Vercel hosts this at /sitemap.xml
 * automatically. Submit it to Google Search Console after deploy.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();

  const routes = [
    { path: '/', priority: 1.0, changeFrequency: 'monthly' as const },
    { path: '/about', priority: 0.9, changeFrequency: 'monthly' as const },
    { path: '/services', priority: 0.9, changeFrequency: 'monthly' as const },
    { path: '/services/strategic-consulting', priority: 0.8, changeFrequency: 'monthly' as const },
    { path: '/services/leadership-development', priority: 0.8, changeFrequency: 'monthly' as const },
    { path: '/services/executive-coaching', priority: 0.8, changeFrequency: 'monthly' as const },
    { path: '/speaking', priority: 0.8, changeFrequency: 'monthly' as const },
    { path: '/insights', priority: 0.7, changeFrequency: 'weekly' as const },
    { path: '/contact', priority: 0.8, changeFrequency: 'monthly' as const },
    { path: '/faq', priority: 0.7, changeFrequency: 'monthly' as const },
    { path: '/privacy', priority: 0.3, changeFrequency: 'yearly' as const },
    { path: '/terms', priority: 0.3, changeFrequency: 'yearly' as const },
  ];

  return routes.map((r) => ({
    url: `${site.url}${r.path}`,
    lastModified,
    changeFrequency: r.changeFrequency,
    priority: r.priority,
  }));
}
